# @package _global_
task_group_name: base

tasks: [generalization_v2]

# Bug: lists don't appear to work only with $ variable passing. Example: [${generalization_v2}] 
# will throw the error: "expected ',' or ']', but got '{' " 
