# @package _global_
model_name: clip-convnext-laion2b-aug

model: 
  _target_: models.clip.clip.CLIPConvNextLaion2BAugClassifierModule
  dataset_to_use_for_classes: ${dataset_to_use_for_class_prompts}
