# @package _global_
model_name: clip-convnextlarge-laion2b

model: 
  _target_: models.clip.clip.CLIPConvNextLargeLaion2BClassifierModule
  dataset_to_use_for_classes: ${dataset_to_use_for_class_prompts}
