# @package _global_
measurement_libary_name: all

#########################################
############ | Properties | #############
#########################################

## -- Equivariance Measures -- ##
equivariance_imagenet_dummy: 
  _target_: measurements.properties.equivariance.equivariance.Equivariance
  datamodule_names: [dummy]
  model: 
  experiment_config:

 
## -- Disentanglement Measures -- ##




##################################################
############ | Downstream Benefits | #############
##################################################

## -- Performance Measures -- ##
validation_imagenet: 
  _target_: measurements.benefits.generalization.ClassificationAccuracyEvaluation
  datamodule_names: [imagenet]
  model: 
  experiment_config:
  
## -- Generalization Measures -- ##
generalization_imagenet_v2: 
  _target_: measurements.benefits.generalization.ClassificationAccuracyEvaluation
  datamodule_names: [v2]
  model: 
  experiment_config:

generalization_imagenet_r: 
  _target_: measurements.benefits.generalization.ClassificationAccuracyEvaluation
  datamodule_names: [imagenet_r]
  model: 
  experiment_config:

generalization_imagenet_a: 
  _target_: measurements.benefits.generalization.ClassificationAccuracyEvaluation
  datamodule_names: [imagenet_a]
  model: 
  experiment_config:

generalization_imagenet_sketch: 
  _target_: measurements.benefits.generalization.ClassificationAccuracyEvaluation
  datamodule_names: [imagenet_sketch]
  model: 
  experiment_config:

generalization_objectnet: 
  _target_: measurements.benefits.generalization.ClassificationAccuracyEvaluation
  datamodule_names: [objectnet]
  model: 
  experiment_config:
  
## -- Fairness Measures -- ##
fairness_dollarstreet: 
  _target_: measurements.benefits.fairness.DollarStreetPerformance
  datamodule_names: [dollarstreet]
  model: 
  experiment_config:

fairness_dollarstreet_kaggle: 
  _target_: measurements.benefits.fairness.DollarStreetPerformance
  datamodule_names: [dollarstreet_kaggle]
  model: 
  experiment_config: