version: 2.1
orbs:
  python: circleci/python@3.9
jobs:
  build-and-test:
    machine: true 
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
workflows:
  sample:
    jobs:
      - build-and-test