version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.1
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
workflows:
  sample:
    jobs:
      - build-and-test
