version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build-and-test:
    executor: python/3.8
    steps:
      - checkout
      - run:
          name: install packages 
          command: pip install -f https://download.pytorch.org/whl/torch_stable.html -e .
      - run:
          name: Run tests
          command: pytest
workflows:
  sample:
    jobs:
      - build-and-test
