version: 2.1
orbs:
  python: circleci/python@2.1.1
executors:
    default2:
        description: The official CircleCI CIMG Python Docker image.
        docker:
            - image: cimg/python:<<parameters.tag >>
        parameters:
            tag:
                default: "3.9"
                description: The `cimg/python` Docker image version tag.
                type: string
jobs:
  build-and-test:
    executor: default2
    steps:
      - checkout
      - run:
          name: install packages 
          command: pip install -f https://download.pytorch.org/whl/torch_stable.html -e .
      - run:
          name: Run tests
          command: pytest -m webtest
          environment:
            USER: meganrichards
workflows:
  sample:
    jobs:
      - build-and-test
