# @package _global_
defaults:
  - base: base
  - mode: local
  - dataset_library: all
  - dataset: dummy
  - model: resnet101 # resnet50, resnet18
  - task_library: all
  - task_group: base
  - property_library: all
  - property_group: base

  