# @package _global_
defaults:
  - base: base
  - mode: cluster_one_gpu
  - dataset_library: all
  - model: resnet50
  - measurement_library: all
  - measurement_group: base

experiment_identifier: fairness