# @package _global_
defaults:
  - base: base
  - mode: cluster_one_gpu
  - dataset_library: all
  - model: clipb16
  - measurement_library: all
  - measurement_group: all

experiment_identifier: new_eval_fixes