# @package _global_
defaults:
  - base: base
  - mode: cluster_one_gpu
  - dataset_library: all
  - model: fvit0
  - measurement_library: all
  - measurement_group: fairness

experiment_identifier: finetuned
dataset_to_use_for_class_prompts: ImageNet
ds_house_separated_only: True
ds_house_separated_and_region_balanced: 