# @package _global_
defaults:
  - base: base
  - mode: cluster_one_gpu
  - dataset_library: all
  - model: resnet18
  - measurement_library: all
  - measurement_group: generalization_fairness

experiment_identifier: more_models