# @package _global_
defaults:
  - base: base
  - mode: cluster_one_gpu
  - dataset_library: all
  - model: clip-coca-vit14
  - measurement_library: all
  - measurement_group: base

experiment_identifier: test
dataset_to_use_for_class_prompts: Imagenet