# @package _global_
defaults:
  - base: base
  - mode: local
  - dataset: dummy
  - model: resnet50_classifier
  - task_library: all 
  - task_group: base
 # - property_library: all
  #- property_group: base

  