# @package _global_
defaults:
  - base: base
  - mode: local_test
  - dataset_library: all
  - model: resnet18 
  - measurement_library: all
  - measurement_group: all

experiment_identifier: test
ds_house_separated_only: True
ds_house_separated_and_region_balanced: 