# @package _global_
task_group_name: base

properties: [disentanglement_dci]


# Bug: lists don't appear to work with $ variable passing. Example: [${generalization_v2}] 
# will throw the error: "expected ',' or ']', but got '{' " 
