# @package _global_
measurement_group_name: all

measurements: [fairness_dollarstreet,generalization_imagenet_v2, 
generalization_imagenet_r, generalization_objectnet, generalization_imagenet_a, generalization_imagenet_sketch, validation_imagenet, equivariance_imagenet_dummy, ]
