# @package _global_
measurement_group_name: all

measurements: [
  fairness_dollarstreet,
  validation_imagenet, generalization_imagenetv2, generalization_imagenetr, generalization_imageneta, generalization_imagenetsketch, generalization_objectnet, 
  equivariance_imagenet, equivariance_imagenetv2, equivariance_imagenetr, equivariance_imageneta, equivariance_imagenetsketch, equivariance_dollarstreet, equivariance_objectnet, 
  sparsity_imagenet, sparsity_imagenetv2, sparsity_imagenetr, sparsity_imageneta, sparsity_imagenetsketch, sparsity_dollarstreet, sparsity_objectnet, 
  nll_imagenet, nll_imagenetv2, nll_imagenetr, nll_imageneta, nll_imagenetsketch, nll_objectnet, 
  ece_imagenet, ece_imagenetv2, ece_imagenetr, ece_imageneta, ece_imagenetsketch, ece_objectnet, 
  ] 
