# @package _global_
measurement_group_name: all

measurements: [equivariance_imagenet, sparsity_imagenet, sparsity_imagenetv2, 
sparsity_imagenetr, sparsity_imageneta, sparsity_imagenetsketch, sparsity_dollarstreet, sparsity_objectnet, sparsity_dollarstreet, validation_imagenet, generalization_imagenetv2, generalization_imagenetr, generalization_objectnet, generalization_imageneta, generalization_imagenetsketch, fairness_dollarstreet ]
