# @package _global_
measurement_group_name: base
measurements: [generalization_imagenetv2] 
#[fairness_dollarstreet, fairness_geode, validation_imagenet, generalization_imagenetv2, generalization_objectnet, generalization_imagenetsketch, generalization_imagenetr, generalization_imageneta]
#[nll_imagenet, nll_imagenetv2, nll_imagenetr, nll_imageneta, nll_imagenetsketch, nll_objectnet, ece_imagenet, ece_imagenetv2, ece_imagenetr, ece_imageneta, ece_imagenetsketch, ece_objectnet]