# @package _global_
task_libary_name: all

###### Generalization Tasks ######
generalization_v2: 
  _target_: tasks.task_utils.StandardEval
  dataset: V2
  metrics: [AUC]


###### Fairness Tasks ######