# @package _global_
task_libary_name: all

###### Performance Tasks ######
validation_imagenet: 
  _target_: tasks.generalization.StandardEval
  dataset_names: [imagenet]
  metrics: [AUC]
  logging_name: 'imagenet'

###### Generalization Tasks ######
generalization_v2: 
  _target_: tasks.generalization.StandardEval
  dataset_names: [v2]
  metrics: [AUC]
  logging_name: 'v2'

###### Fairness Tasks ######