# @package _global_
dataset_name: shapenet_individual_image_sampling

datamodule:
  _target_: datasets.shapenet.shapenet_v2.ShapeNetv2SingleFactorDataModule
  batch_size: 32
  num_workers: 4
  train_prop_to_vary: 0.5
  factor_to_vary: Rotation