# @package _global_
property_libary_name: all

###### Equivariance Measures ######
equivariance_aug: 
  _target_: properties.equivariance.AugmentationEquivariance
  logging_name: 'equivariance_aug'
 
###### Disentanglement Measures ######
disentanglement_dci: 
  _target_: properties.disentanglement.DCI
  logging_name: 'disentanglement_dci'
