# @package _global_
dataset_libary_name: all

###### Testing ######
dummy:
  _target_: datasets.dummy.DummyDataModule
  batch_size: 8
  num_classes: 1000
 
###### Imagenet & Variants ######
imagenet:
  _target_: datasets.imagenet_1k.ImageNet1kDataModule
  batch_size: 32
  num_workers: 4

v2:
  _target_: datasets.image_datamodule.ImageDataModule
  data_dir: /checkpoint/meganrichards/datasets/imagenetv2-matched-frequency/
  batch_size: 32
  num_workers: 4

imagenet_r:
  _target_: datasets.imagenet_rendition.ImageNetRenditionDataModule
  batch_size: 32
  num_workers: 4

imagenet_a:
  _target_: datasets.imagenet_adversarial.ImageNetAdversarialDataModule
  data_dir: /checkpoint/meganrichards/datasets/imagenet_a/
  batch_size: 32
  num_workers: 4

imagenet_sketch:
  _target_: datasets.imagenet_sketch.ImageNetSketchDataModule
  data_dir: /checkpoint/meganrichards/datasets/imagenet_sketch/
  batch_size: 32
  num_workers: 4

objectnet:
  _target_: datasets.objectnet.ObjectNetDataModule
  data_dir: /checkpoint/meganrichards/datasets/objectnet/
  batch_size: 32
  num_workers: 4

###### Fairness ######
# dollarstreet-old:
#   _target_: datasets.dollarstreet.DollarStreetDataModule
#   data_dir: /checkpoint/meganrichards/datasets/dollarstreet_interplay/
#   batch_size: 32
#   num_workers: 8

dollarstreet:
  _target_: datasets.dollarstreet_kaggle.DollarStreetDataModule
  data_dir: /checkpoint/meganrichards/datasets/dollarstreet_kaggle/dataset_dollarstreet/
  batch_size: 32
  num_workers: 8


